back/back/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("user/", include('users.urls')),
]

back/home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.view_main, name='view_main'),
]

back/users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

back/home/models.py
from django.db import models

# Create your models here.

back/users/models.py
from django.db import models

# Create your models here.

back/home/views.py
from django.shortcuts import render

# Create your views here.
def view_main(request):
    return render(request, 'main.html')

back/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib import auth

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password1'],
                email=request.POST['email'],
            )
            
            auth.login(request, user)
            return redirect('/')
        return render(request, 'signup.html')
    return render(request, 'signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        return render(request, 'login.html', {'error': 'username or password is incorrect.'})
    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

back/home/templates/main.html
{% extends 'base.html' %}

{% comment %} content {% endcomment %}

{% block content %}

  <div id='top-event'>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="2000">
          <p class='event-text'>이벤트가 있다면</p>
        </div>
        <div class="carousel-item">
          <p class='event-text'>여기에서</p>
        </div>
        <div class="carousel-item">
          <p class='event-text'>확인할 수 있습니다.</p>
        </div>
      </div>
    </div>
  </div>

  <div id='nav-bar'>
      <div class='nav-item-div'>
        <div class="nav-text-div">
          {% if user.is_authenticated %}
            <p class='nav-text'>{{request.user.username}}</p>
            <a href="{% url 'users:logout' %}"  class='nav-text'>logout</a>
          {% else %}
            <a href="{% url 'users:signup' %}" class='nav-text'>signin</a>
            <a href="{% url 'users:login' %}" class='nav-text'>login</a>
          {% endif %}
        </div>
      </div>

      <div class='nav-item-div'>
        {% comment %} <div class='nav-image-div'>nav-image</div> {% endcomment %}
        <div class="nav-text-div">
          <p class='nav-text'>nav-text</p>
        </div>
      </div>

      <div class='nav-item-div'>
        {% comment %} <div class='nav-image-div'>nav-image</div> {% endcomment %}
        <div class="nav-text-div">
          <p class='nav-text'>nav-text</p>
        </div>
      </div>
  </div>

  <div id="carousel-div">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active"  data-bs-interval="3000">
          <img class="carousel-custom-img" src="https://file.newswire.co.kr/data/datafile2/thumb_640/2021/06/990366635_20210628162512_8318036088.jpg">
        </div>
        <div class="carousel-item">
          <img class="carousel-custom-img" src="https://www.koreafurniture.com/data/mainbrand/10">
        </div>
        <div class="carousel-item">
          <img class="carousel-custom-img" src="https://unogagu.com/wp-content/uploads/2022/06/IMGL8149-2-scaled.jpg">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

  <div id="bottom-bar">
    <p id="bottom-bar-text">
      @네이버 커넥트재단
    </p>
  </div>
{% endblock content %}

{% comment %} css {% endcomment %}

{% block css %}

#top-event{
  width: 100vw;
  height: 5vh;

  background-color: #7986AC;
  text-align: center;
  line-height : 5vh;
}

.event-text{
  margin: 0;
  color: #FFD3AA;
}

#nav-bar{
  width: 100vw;
  height: 8vh;

  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;

  {% comment %} border: 1px white solid; {% endcomment %}
}

.nav-item-div{
  height: 10vh;

  margin: 0;

  display: flex;
  flex-direction: row;
  justify-content: start;
  align-items: center;

  {% comment %} border: 1px solid red; {% endcomment %}
}

.nav-image-div{
  height: 10vh;
  width: 10vh;
  object-fit: cover;

  display: flex;
  justify-content: center;
  align-items: center;

  font-size: 100%;
  color: #7986AC;
  {% comment %} border: 1px solid blue; {% endcomment %}
}

.nav-text-div{
  height: 10vh;
  width: 10vh;
  
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  flex-grow: 1;
}

.nav-text{
  margin: 0 0 0 3%;

  color: #7986AC;
}

#carousel-div{
  height: 70vh;
  width: 80vw;
}

.carousel-custom-img{
  height: 70vh;
  width: 80vw;

  border: 5px solid #AA6F39;
}

#bottom-bar{
  height: 5vh;
  width: 100vw;

  background-color: #7683AA;

  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}

#bottom-bar-text{
  margin: 0;
  color: #FFD3AA;
}
{% endblock css %}

back/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  
  {% endblock head %}
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GukBob</title>
</head>
<body>
  <div id="backgrond-div">
    {% block content %}

    {% endblock content %}
  </div>
</body>
</html>

<style>
  #backgrond-div {
    background-color: #50608F;
    position : absolute;
    left: 0;
    top: 0;

    width: 100vw;
    height: 100vh;

    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items : center;
  }

  {% block css %}

  {% endblock css %}
</style>

back/users/templates/login.html
{% extends 'base.html' %}

{% block head %}

{% endblock head %}

{% comment %} content {% endcomment %}

{% block content %}

<div id="login_background_div">
  <div id='login_inner_div'>
    <h1>로그인</h1>
    <form method="POST">
        {% csrf_token %}
        아이디:
        <br>
        <input name="username" type="text">
        <br>
        비밀번호:
        <br>
        <input name="password" type="password">
        <br><br>
        <input type="submit" class="btn" value="Login">
    </form>
  </div>
</div>

{% endblock content %}

{% comment %} css {% endcomment %}

{% block css %}

#login_background_div{
  height: 100vh;
  width: 100vw;

  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

#login_inner_div{
  height: 50vh;
  width: 20vw;

  display: flex;
  flex-direction: column;
  justify-content: start;
  align-items: center;

  padding-top: 10vh;

  background-color: rgba(255, 255, 255, 0.2);

  border: 3px solid rgba(255, 255, 255, 0.3);
  border-radius: 10px 10px 10px 10px / 5px 5px 5px 5px;
}

{% endblock css %}

back/users/templates/signup.html
{% extends 'base.html' %}

{% block head %}

{% endblock head %}

{% comment %} content {% endcomment %}

{% block content %}

<div>
  <h1>회원가입</h1>
  <form method="POST">
      {% csrf_token %}
      아이디: <br>
      <input name="username" type="text">
      <br>
      비밀번호: <br>
      <input name="password1" type="password">
      <br>
      비밀번호 확인: <br>
      <input name="password2" type="password">
      <br>
      이메일: <br>
      <input name="email" type="email">
      <br><br>
      <input type="submit" class="btn btn-primary" value="Sign Up">
  </form>
</div>

{% endblock content %}

{% comment %} css {% endcomment %}

{% block css %}



{% endblock css %}